// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: sqrt.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Squre {
  public static partial class SquareRootService
  {
    static readonly string __ServiceName = "squre.SquareRootService";

    static readonly grpc::Marshaller<global::Squre.Request> __Marshaller_squre_Request = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Squre.Request.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Squre.Response> __Marshaller_squre_Response = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Squre.Response.Parser.ParseFrom);

    static readonly grpc::Method<global::Squre.Request, global::Squre.Response> __Method_CalculateSquare = new grpc::Method<global::Squre.Request, global::Squre.Response>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CalculateSquare",
        __Marshaller_squre_Request,
        __Marshaller_squre_Response);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Squre.SqrtReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of SquareRootService</summary>
    [grpc::BindServiceMethod(typeof(SquareRootService), "BindService")]
    public abstract partial class SquareRootServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Squre.Response> CalculateSquare(global::Squre.Request request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for SquareRootService</summary>
    public partial class SquareRootServiceClient : grpc::ClientBase<SquareRootServiceClient>
    {
      /// <summary>Creates a new client for SquareRootService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public SquareRootServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for SquareRootService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public SquareRootServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected SquareRootServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected SquareRootServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Squre.Response CalculateSquare(global::Squre.Request request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CalculateSquare(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Squre.Response CalculateSquare(global::Squre.Request request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CalculateSquare, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Squre.Response> CalculateSquareAsync(global::Squre.Request request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CalculateSquareAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Squre.Response> CalculateSquareAsync(global::Squre.Request request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CalculateSquare, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override SquareRootServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new SquareRootServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(SquareRootServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_CalculateSquare, serviceImpl.CalculateSquare).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, SquareRootServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_CalculateSquare, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Squre.Request, global::Squre.Response>(serviceImpl.CalculateSquare));
    }

  }
}
#endregion
